app:
  name: "vercelc"
  environment: "local"

upload_service:
  web:
    upload_service_hostname: "localhost"
    upload_service_port: 8000

s3:
  accesskey: ""
  secretkey: ""
  region: "ap-south-1"
