app:
  name: "vercelc"
  environment: "local"

uploadservice:
  web:
    hostname: "localhost"
    port: 8000

s3:
  accesskey: ""
  secretkey: ""
  region: "ap-south-1"
  bucket: "vercelc"

redis:
  hostname: "localhost"
  port: 6379
  queue: "build-queue"
